### PR TITLE
Feature/exact ephs

### PR DESCRIPTION
**Pull request by rhiannonlynne**
This PR significantly updates the generation of observations.
It adds the capability to generate observations at the exact time of each observation, rather than just using a linear interpolation over a grid of times.
It also adds the option to use a rectangular footprint, as well as the circular and camera footprints.
makeLSSTobs.py has added more options to take advantage of these new capabilities.
The final output observations now contain metadata regarding their generation.
Updated examples notebooks.

### CODE REVIEW

**Comment by yoachim** [comment]
One issue, my eups didn't have `pandas` and it's not an intuitive thing to trick eups into installing it (turns out you need to specify a version). Maybe easiest solution is to just add `setupRequired(pandas)` to the `lsst_sims` table? Then it should get taken care of like numpy, etc.

Unit tests are failing all over the place (same way on my local install and if I try it in docker).

The example notebooks run great! Maybe put instructions to sym-link the opsim sqlite into the example directory, then you can remove your hard-coded path.

**Comment by rhiannonlynne** [comment]
I'm not sure I understand about "your eups doesn't have pandas" -- are you using the LSST miniconda? The LSST miniconda comes with pandas now.

**Comment by yoachim** [comment]
yup, I have pandas with miniconda. But if pandas is in the ups table file there needs to be a stub package for eups to "setup". Just like there's a numpy one even though numpy comes with conda.

**Comment by rhiannonlynne** [comment]
But pandas is in the table file already?

**Comment by rhiannonlynne** [comment]
(it's in the table file for sims_movingObjects)

**Comment by yoachim** [comment]
Seems like it's going to be hard to get anyone else to use it if you require lsstsw to install. I guess if you're planning on publishing a build, then that solves the problem.

**Comment by rhiannonlynne** [comment]
It's hard to get anyone to use it even if you just "eups distrib install" following "newinstall" (which we can do, publishing a build is fine ... it's just not been published yet or if it has, it's a very old build). 

TBH, from what I've seen, lsstsw is currently in better working shape than newinstall. They go back and forth though.

But yeah - publishing a docker build is good, and access on jupyterhub is better (see https://epyc.astro.washington.edu/sssc/hub/login for the SSSC)

**Comment by rhiannonlynne** [comment]
For what you want to do right now - get pandas installed -- I think you should be able to do "eups distrib install pandas" maybe?

**Comment by yoachim** [comment]
turns out one needs to do 'eups distrib install pandas -v master-g4426870190`.

**Comment by rhiannonlynne** [comment]
The unit test failures were rather stupid problems. Fixed.

**Comment by rhiannonlynne** [comment]
https://ci.lsst.codes/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/28764/pipeline in progress

**Comment by rhiannonlynne** [comment]
Merged and deleted feature/exact_ephs

**Pull request merged**
